# Generated by Django 3.2.8 on 2022-03-23 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
